codecov:
  require_ci_to_pass: yes

ignore:
  - "src/test/**"
  - "src/main/java/org/izrak/Main.java"
  - "src/main/java/org/izrak/export/Exporter.java"
  - "src/main/java/org/izrak/parsing/InputParser.java"

